name: 'Validate YAML Files'
# Currently we are only validating if the there are any breaking errors
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint . --format github
